### ISSUE TITLE
processInputs does not process dict (HTTPRequest.record) types

### ISSUE THREAD

**Issue by petschki** [zopefoundation/plone.z3cform#24]
I came across this here https://github.com/plone/plone.app.caching/pull/49 because the controlpanel has several inputs with `:record` in its name. Those inputs get processed as `zPublisher.HTTPRequest.record` objects and are not considered here. Therefore the values are still `binary_types` and break the z3c.form ... I'm wondering that this was no problem earlier?

/cc @pbauer @ale-rt @davisagli  do you agree to take this type into account while processing? If yes I'll create a pull request.

**Comment by pbauer** [comment]
I saw the same issue and wondered the same. So I have no opinion if `:record` is the problem and should be changed or if `processInputs` should handle that.

**Comment by petschki** [comment]
Merged in fork https://github.com/plone/plone.z3cform/pull/1
