### ISSUE TITLE
move to the plone namespace

### ISSUE THREAD

**Issue by saily** [zopefoundation/plone.z3cform#3]
Why this is zopefoundation with plone in it's package name? Shouldn't it be moved to plone?

**Comment by jensens** [comment]
+1

**Comment by MatthewWilkes** [comment]
Looks like @dnouri moved this to the Zope repo between versions 0.2 and 0.3. I'm pretty sure the Plone foundation didn't agree to that, so this was a violation of the Zope contributor agreement.

Before this can be moved back to the Plone repository we would need an opinion from the Plone Foundation board. As I see it, we will need to audit this for contributors that haven't signed the Plone contributor agreement, and also get a waiver from the Zope foundation.

**Comment by dnouri** [comment]
@MatthewWilkes Despite the "plone" in the name, this was never Plone foundation code.  It was checked in to the Collective, not the Plone repository, before I moved it to Zope.

**Comment by MatthewWilkes** [comment]
I'm sorry, I was basing it on http://svn.plone.org/svn/plone/plone.z3cform/

I'm not at a computer right now, can someone else cc in whoever moved it from the collective without authorisation from the rights holders.

**Comment by davisagli** [comment]
IIRC I think it was @optilude and I'm pretty sure I remember him asking for permission from contributors.

**Comment by dnouri** [comment]
I must be remembering this wrong then.  This package sure has an interesting history.  :-)

**Comment by petschki** [comment]
as discussed here https://github.com/plone/buildout.coredev/issues/139 there's a new fork on `/plone` and we'll move this repo into ARCHIVED/READONLY state from now on.
